apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-demo-api
  namespace: devops-demo
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: devops-demo-api
  namespaceSelector:
    matchNames:
      - devops-demo
  endpoints:
    - port: http
      path: /metrics
      interval: 15s

